### ISSUE TITLE
CSS 如何实现水平垂直居中

### ISSUE THREAD

**Issue by Reaper622** [mis-lab/Front-End-Question-Discussion#23]
- absolute + 负 margin 「需要定宽高」

```css
.box{
  position: absolute;
  top: 50%;
  left: 50%;
  width: 100px;
  height: 100px;
  margin-top: -50px;
  margin-left: -50px;
}
```

- absolute + margin auto 「需要定宽高」

```css
.box{
	position: absolute;
  top: 0;
  left: 0;
  width: 100px;
  height: 100px;
  right: 0;
  bottom: 0;
  margin: auto;
}
```

- absolute + transform(百分比参考自身)

```css
.box{
  position: absolute;
  width:100px;
  height: 100px;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%)
}
```

- line-height  利用行内元素和基线居中

```css
.container {
  position: relative;
  text-align: center;
  line-height: 300px;
  font-size: 0px;
}

.box{
  font-size: 16px;
  width: 100px;
  height: 100px;
  display: inline-block;
  vertical-align: middle;
  line-height: initial;
  text-align: left; /* 修正文字 */
}
```

- flex

```css
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;  /*注意给父元素设置高度，负责垂直居中会失效*/
}
```

- grid

```css
.container {
  display: grid;
  height: 100%;
}

.box{
  width: 100px;
  height: 100px;
  align-self: center;
  justify-self: center;
}
```
